const { createGlobPatternsForDependencies } = require('@nx/react/tailwind');
const { join } = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    join(__dirname, '{src,pages,components,app}/**/*!(*.stories|*.spec).{ts,tsx,html}'),
    ...createGlobPatternsForDependencies(__dirname),
    '../../libs/auth/src/**/*.{ts,tsx}',
    '../../libs/ui/src/**/*.{ts,tsx}',
    '../../libs/shared/src/**/*.{ts,tsx}',
  ],
  safelist: [
    // Gradient backgrounds
    'bg-gradient-to-b',
    'bg-gradient-to-br',
    'bg-gradient-to-tr',
    'bg-gradient-to-bl',
    'bg-gradient-to-r',
    'bg-gradient-to-tl',
    // Purple shades
    'from-purple-300',
    'from-purple-400',
    'from-purple-500',
    'from-purple-600',
    'from-purple-700',
    'from-purple-800',
    'from-purple-900',
    'via-purple-300',
    'via-purple-400',
    'via-purple-500',
    'via-purple-600',
    'via-purple-700',
    'via-purple-800',
    'via-purple-900',
    'to-purple-300',
    'to-purple-400',
    'to-purple-500',
    'to-purple-600',
    'to-purple-700',
    'to-purple-800',
    'to-purple-900',
    // Violet shades
    'from-violet-500',
    'from-violet-600',
    'from-violet-700',
    'from-violet-800',
    'from-violet-900',
    'via-violet-500',
    'via-violet-600',
    'via-violet-700',
    'via-violet-800',
    'via-violet-900',
    'to-violet-500',
    'to-violet-600',
    'to-violet-700',
    'to-violet-800',
    'to-violet-900',
    // Pink shades
    'from-pink-300',
    'from-pink-400',
    'from-pink-500',
    'from-pink-600',
    'from-pink-700',
    'from-pink-800',
    'from-pink-900',
    'via-pink-300',
    'via-pink-400',
    'via-pink-500',
    'via-pink-600',
    'via-pink-700',
    'via-pink-800',
    'via-pink-900',
    'to-pink-300',
    'to-pink-400',
    'to-pink-500',
    'to-pink-600',
    'to-pink-700',
    'to-pink-800',
    'to-pink-900',
    // Fuchsia shades
    'from-fuchsia-400',
    'from-fuchsia-500',
    'from-fuchsia-600',
    'from-fuchsia-700',
    'from-fuchsia-800',
    'from-fuchsia-900',
    'via-fuchsia-400',
    'via-fuchsia-500',
    'via-fuchsia-600',
    'via-fuchsia-700',
    'via-fuchsia-800',
    'via-fuchsia-900',
    'to-fuchsia-400',
    'to-fuchsia-500',
    'to-fuchsia-600',
    'to-fuchsia-700',
    'to-fuchsia-800',
    'to-fuchsia-900',
    // Rose shades
    'from-rose-300',
    'from-rose-400',
    'from-rose-500',
    'from-rose-600',
    'from-rose-700',
    'from-rose-800',
    'from-rose-900',
    'via-rose-300',
    'via-rose-400',
    'via-rose-500',
    'via-rose-600',
    'via-rose-700',
    'via-rose-800',
    'via-rose-900',
    'to-rose-300',
    'to-rose-400',
    'to-rose-500',
    'to-rose-600',
    'to-rose-700',
    'to-rose-800',
    'to-rose-900',
    // Fuchsia additional
    'to-fuchsia-200',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        purple: "hsl(var(--purple))",
        "magenta-light": "hsl(var(--magenta-light))",
        magenta: "hsl(var(--magenta))",
        error: "hsl(var(--error))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      backgroundImage: {
        "gradient-button":
          "linear-gradient(19deg, #FEBEFA 6.78%, #B339D4 34.87%, #7B21BA 61.32%, #7B26F0 91.07%)",
        "gradient-glass":
          "linear-gradient(198deg, rgba(38, 38, 38, 0.30) 10.03%, rgba(19, 19, 19, 0.30) 75.61%)",
        "radial-glow":
          "radial-gradient(50% 50% at 50% 50%, #D497FF 0%, #7B21BA 100%)",
        "gradient-dark-purple": "linear-gradient(to bottom, rgb(88, 28, 135), rgb(126, 58, 148), rgb(168, 85, 247))",
        "gradient-midnight-purple": "linear-gradient(to bottom right, rgb(88, 28, 135), rgb(107, 33, 168), rgb(147, 51, 234))",
        "gradient-deep-violet": "linear-gradient(to top right, rgb(76, 29, 149), rgb(109, 40, 217), rgb(139, 92, 246))",
        "gradient-royal-purple": "linear-gradient(to bottom left, rgb(107, 33, 168), rgb(147, 51, 234), rgb(168, 85, 247))",
        "gradient-plum-rose": "linear-gradient(to right, rgb(147, 51, 234), rgb(219, 39, 119), rgb(244, 63, 94))",
        "gradient-lavender-pink": "linear-gradient(to bottom right, rgb(196, 181, 253), rgb(251, 207, 232), rgb(253, 164, 175))",
        "gradient-magenta-purple": "linear-gradient(to top right, rgb(190, 24, 93), rgb(147, 51, 234), rgb(107, 33, 168))",
        "gradient-berry-purple": "linear-gradient(to bottom left, rgb(225, 29, 72), rgb(219, 39, 119), rgb(126, 58, 148))",
        "gradient-amethyst": "linear-gradient(to right, rgb(126, 58, 148), rgb(124, 58, 237), rgb(168, 85, 247))",
        "gradient-cosmic-purple": "linear-gradient(to bottom right, rgb(88, 28, 135), rgb(126, 58, 148), rgb(219, 39, 119))",
        "gradient-twilight": "linear-gradient(to top right, rgb(88, 28, 135), rgb(190, 24, 93), rgb(236, 72, 153))",
        "gradient-orchid": "linear-gradient(to bottom left, rgb(168, 85, 247), rgb(236, 72, 153), rgb(244, 114, 182))",
        "gradient-diagonal-purple": "linear-gradient(to bottom right, rgb(107, 33, 168), rgb(217, 70, 239), rgb(196, 181, 253))",
        "gradient-reverse-purple": "linear-gradient(to top left, rgb(196, 181, 253), rgb(236, 72, 153), rgb(107, 33, 168))",
        "gradient-intense-purple": "linear-gradient(to bottom, rgb(107, 33, 168), rgb(109, 40, 217), rgb(88, 28, 135))",
        "gradient-soft-purple": "linear-gradient(to right, rgb(196, 181, 253), rgb(251, 207, 232), rgb(196, 181, 253))",
      },
      fontFamily: {
        sans: ["Inter", "unused-sans-serif", "system-unused", "sans-serif"],
        inter: ["Inter", "unused-sans-serif", "system-unused", "sans-serif"],
        "mier-a": ["Mier A", "unused-sans-serif", "system-unused", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      spacing: {
        'sidebar': '16rem',
        'sidebar-collapsed': '3rem',
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
        'sidebar-expand': {
          from: { width: '3rem' },
          to: { width: '16rem' },
        },
        'sidebar-collapse': {
          from: { width: '16rem' },
          to: { width: '3rem' },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        'sidebar-expand': 'sidebar-expand 0.2s ease-out',
        'sidebar-collapse': 'sidebar-collapse 0.2s ease-out',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
